name: binwalk-spirotot
summary: Biwnalk Snap 
version: master
description: | 
    Binwalk is a fast, easy to use tool for analyzing, reverse
    engineering, and extracting firmware images.

grade: stable
confinement: strict

apps:
    binwalk:
        command: usr/local/bin/binwalk
        plugs: [home, fuse-support]

parts:
   python-build:
        source: https://github.com/devttys0/binwalk.git
        source-branch: master
        stage-packages: [python-pip, python-setuptools, python-lzma, python-lzo, python-crypto, libqt4-opengl, python-opengl, python-qt4, python-qt4-gl, python-numpy, python-scipy, mtd-utils, gzip, bzip2, tar, arj, lhasa, p7zip, p7zip-full, cabextract, cramfsprogs, cramfsswap, sleuthkit, default-jdk, lzop, srecord, squashfuse, squashfs-tools, zlib1g-dev, liblzma-dev, liblzo2-dev]
        plugin: python
        python-version: python2
        python-packages: [matplotlib, capstone, ubi-reader]
        prepare: |
            pip install --upgrade pip; \
            pip install -U setuptools; \
            ./deps.sh --yes; \
            cp /usr/local/bin/sasquatch ../install/usr/local/bin/; \
            cp /usr/local/bin/unstuff ../install/usr/local/bin/;  \
            mkdir -p ../install/etc/ssl/certs/java/; \
            /bin/cp -f /etc/ssl/certs/java/cacerts ../install/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts;

            # ^--- Error while processing...
            # The store was unable to accept this snap.
            #   - package contains external symlinks: usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
            #cp /usr/local/bin/ubi* ../install/usr/local/bin/
        build: |
             python2 setup.py install
